# TD 1 | Introduction à Python pour l'analyse de données

---

Objectifs du TD :

* découvrir Python
* se familiariser avec le langage et le notebook Jupyter
* découvrir et maîtriser les bases des librairies de calcul numérique et d'analyse de données numpy et pandas

---

##  Installation de Python et Jupyter

### Windows

#### Installation Python

Vérifiez si vous avez déjà une version de python installée en ouvrant l'invite de commande et en exécutant l'une des deux commandes python suivantes : 
> python --version   

> python3 --version 

Si ce n'est pas le cas, vous pouvez procéder à l'installation comme suit :
 
1. Allez sur le site web : https://www.python.org/downloads/windows/
2. Cliquez sur "Latest Python 3 Release - Python 3.10.7".
3. Si votre ordinateur utilise une version 64 bits de Windows, téléchargez le Windows installer (64-bit). Sinon, téléchargez Windows installer (32-bit).
4. Après avoir téléchargé le Windows installer, vous devez l'exécuter (double-cliquez dessus) et suivre les instructions qui s'y trouvent.

NB : Au début de l'installation, assurez-vous de cocher la case "Add Python 3.10 to PATH" ou "Add Python to your environment variables" avant de cliquer sur "Install Now".


#### Installation Jupyter

Ouvrir l'invite de commande et exécuter la commande suivante en remplaçant Pseudo_de_votre_user par le nom de l'utilisateur de votre session : 
> cd "C:\Users\Pseudo_de_votre_user\AppData\Local\Programs\Python\Python310\Scripts"

Ensuite, executer la commande suivante :
> pip install jupyterlab

Une fois l'installation terminée avec succès, vous pouvez lancer JupyterLab avec la commande suivante : 
> jupyter-lab


### Linux & Mac OS

#### Installation Python

Normalement, Python est préinstallé sur la quasi-totalité des distributions. Vous n'avez pas besoin de le réinstaller, mais vous pouvez mettre à jour la version si vous le souhaitez.

Vérifiez la version Python installée en exécutant l'une des deux commandes python suivantes sur votre terminal : 
> python --version   

> python3 --version 

#### Installation Jupyter

Vérifier que la commande pip3 est installée. Sinon, l'installer (exemple pour Debian/Ubuntu/Linux Mint, à adapter selon votre distribution) :

> sudo apt install python3-pip

Ensuite, installer JupyterLab en executant la commande suivante:
> pip3 install -U jupyterlab

Enfin, placez-vous dans votre dossier de travail et lancez un notebook :

> jupyter-lab

## Syntaxe et Concepts de base

In [1]:
a = 33
b = 9
c = 2.0

In [2]:
a+b

42

In [3]:
print(a+b)

42


In [4]:
type(a)

int

In [5]:
type(c)

float

In [6]:
a = 'hello'
type(a)

str

In [7]:
# Affiche les entiers pairs de 1 à 10
for i in range(1, 11):
    if i % 2 == 0:
        print(i)

2
4
6
8
10


### List

In [8]:
l = [1,2,3,4,4]

#### len, max, min

In [9]:
print('longueur de la liste =', len(l))
print("Valeur max de l =", max(l))
print("Valeur min de l =", min(l))

longueur de la liste = 5
Valeur max de l = 4
Valeur min de l = 1


#### Ajout d'un élément d'une liste

In [10]:
l.append(6)
l

[1, 2, 3, 4, 4, 6]

In [11]:
l = l+[7]
l

[1, 2, 3, 4, 4, 6, 7]

In [12]:
l+=[7]
l

[1, 2, 3, 4, 4, 6, 7, 7]

#### Modifier un élément

In [13]:
l[0] = 29
l

[29, 2, 3, 4, 4, 6, 7, 7]

In [14]:
l.insert(1,9)
l

[29, 9, 2, 3, 4, 4, 6, 7, 7]

#### Suppression des éléments d'une liste

In [15]:
l.remove(7)
l

[29, 9, 2, 3, 4, 4, 6, 7]

In [16]:
l.pop(2)
l

[29, 9, 3, 4, 4, 6, 7]

#### Trier une liste

In [17]:
l.sort(reverse=True)
print(l)

[29, 9, 7, 6, 4, 4, 3]


In [18]:
l_sorted = sorted(l)
print('Sorted list:', l_sorted)

Sorted list: [3, 4, 4, 6, 7, 9, 29]


#### Liste non homogène

In [19]:
l = [1, 'un', 2]
l.append('deux')
l += [3, 'trois']
print(type(l))
l

<class 'list'>


[1, 'un', 2, 'deux', 3, 'trois']

In [20]:
a = l[3], l[-1]
print(type(a))
a

<class 'tuple'>


('deux', 'trois')

In [21]:
a[0]

'deux'

In [22]:
[2**p for p in range(10)] # "Compréhension de liste"

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512]

In [23]:
# Liste des entiers pairs de 1 à 10
l = [i for i in range(1, 11) if i % 2 == 0]
print(l)

[2, 4, 6, 8, 10]


### Tuple

In [24]:
p = tuple(range(1,5))
print("p=", p)
print("p[0] = ", p[0])

p= (1, 2, 3, 4)
p[0] =  1


In [25]:
p = ([1,2],5)

print(p)

p[0][0] = 8

print(p)

([1, 2], 5)
([8, 2], 5)


In [26]:
# Les éléments du tuple sont fixes
p[0] = 6

TypeError: 'tuple' object does not support item assignment

In [27]:
p1 = (1,2)
p2 = (2,1)

print(p1 == p2)

False


### Set

In [28]:
s = set((1,2,'l'))
print(s)

s = {4,5,9,9,9,9}
print(s)

{1, 2, 'l'}
{9, 4, 5}


In [29]:
#Ajout d'un élément au set
s.add(6)
print(s)

{9, 4, 5, 6}


In [30]:
#Suppression d'un élément du set
s.discard(5)
print(s)

{9, 4, 6}


In [31]:
s.clear()
print(s)

set()


In [32]:
A = {1,2,3,4,5}
B = {2,4,6,7}
C = {1,2,3}

In [33]:
#Intersection
print("Intersection de A et B =", A&B)

#Union
print("Union entre A et B =", A|B)

#Exclusion
print("Exclusion de B de A =", A-B)

#Différence symétrique
print("Diff sym. A et B =", A^B)

Intersection de A et B = {2, 4}
Union entre A et B = {1, 2, 3, 4, 5, 6, 7}
Exclusion de B de A = {1, 3, 5}
Diff sym. A et B = {1, 3, 5, 6, 7}


In [34]:
print("B est inclus strict dans A") if A>B else print(False)
print("C est inclus dans A") if A>=C else print(False)

False
C est inclus dans A


### Dictionary

In [35]:
# 1ère façon de créer un dictionnaire
dic = {"key1": "value1", "answer": 42}
# 2ème façon de créer un dictionnaire
dic2 = dict(key1="value1", answer=42)
# 3ème façon de créer un dictionnaire
dic3 = dict([("key1","value1"), ("answer",42)])
print(dic)
print(dic2)
print(dic3)

dic["answer"]

{'key1': 'value1', 'answer': 42}
{'key1': 'value1', 'answer': 42}
{'key1': 'value1', 'answer': 42}


42

In [36]:
dic['new'] = [1,2,3]

In [37]:
dic.keys()

dict_keys(['key1', 'answer', 'new'])

In [38]:
dic.items()

dict_items([('key1', 'value1'), ('answer', 42), ('new', [1, 2, 3])])

In [39]:
dic.values()

dict_values(['value1', 42, [1, 2, 3]])

In [40]:
a,b,c = dic.items()
print(a)

('key1', 'value1')


## Programmation Orientée Objet

In [41]:
"""
Exemple de classe en Python
"""
class Moteur:
    
    # Constructeur
    def __init__(self, esn, panne=False):
        self.esn = esn
        self.panne = panne
    
    # Méthodes
    def dire_bonjour(self):
        print('Bonjour, mon numéro de série est ' + self.esn)
    
    def fonctionne(self):
        return not self.panne 
    

In [42]:
mot1 = Moteur('420912')
mot2 = Moteur(panne=True, esn='420913')

mot1.dire_bonjour()
print(mot1.fonctionne())

mot1.panne = True
print(mot1.fonctionne())

print('\n')
mot2.dire_bonjour()
print(mot2.fonctionne())

Bonjour, mon numéro de série est 420912
True
False


Bonjour, mon numéro de série est 420913
False


### Méthode récurcive vs Méthode itérative

In [43]:
# Méthode récursive
def fact1(n):
    if n == 0:
        return 1
    else:
        return n*fact1(n-1)

# Méthode itérative
def fact2(n):
    s=1
    for i in range(1,n+1):
        s*=i
    return s

print(fact1(5))
print(fact2(5))

120
120


In [44]:
"""
App.1 : Ecrire une fonction qui retourne le plus grand commun diviseur (pgcd) entre deux nombres a et b.
"""

def pgcd(a,b):
    while(a%b!=0):
        m=a%b
        a=b
        b=m
    return b 
print(pgcd(31,6))


1


In [45]:
"""
App.1 : Correction
"""

#Méthode itérative
def pgcd1(a,b):
    while (a%b) != 0:
        s = a%b
        a = b
        b = s
    return b


#Méthode récurcive
def pgcd2(a,b):
    if a==b : return a 
    if a<b : a,b = b,a
    return pgcd(a-b,b)

a = 230
b = 25

print("pgcd1(a,b) = ", pgcd1(a,b))
print("pgcd2(a,b) = ", pgcd2(a,b))

pgcd1(a,b) =  5
pgcd2(a,b) =  5


## Libraries

> pip install numpy pandas

> pip3 install -U numpy pandas

### Math

In [46]:
import math

In [47]:
x = 4

print("sqrt(x) =", math.sqrt(x))
print("cos(x) =", math.cos(x))
print("sin(x) =", math.sin(x))
print("factorial(x) =", math.factorial(x))

sqrt(x) = 2.0
cos(x) = -0.6536436208636119
sin(x) = -0.7568024953079283
factorial(x) = 24


### Numpy

In [48]:
import numpy as np

In [49]:
# Création d'un array à partir d'une liste
v = np.array([1.0, 2.0, 3.0])
# Création d'un array de taille (n,m) initialisé à 0
z = np.zeros((3,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
# Taille d'un array
print(z.shape)
print(v.shape)

(3, 4)
(3,)


In [51]:
# Opérations courantes
A = np.ones((3,3)) + np.eye(3)
print('A = ', A)
print('Av = ', np.dot(A,v))
print('3*A = ', 3*A)
print('A*v = ', A*v)
print('A + 1 = ', A+1)
print('A + v = ', A+v)
print('A^2 = ', np.square(A))

A =  [[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
Av =  [7. 8. 9.]
3*A =  [[6. 3. 3.]
 [3. 6. 3.]
 [3. 3. 6.]]
A*v =  [[2. 2. 3.]
 [1. 4. 3.]
 [1. 2. 6.]]
A + 1 =  [[3. 2. 2.]
 [2. 3. 2.]
 [2. 2. 3.]]
A + v =  [[3. 3. 4.]
 [2. 4. 4.]
 [2. 3. 5.]]
A^2 =  [[4. 1. 1.]
 [1. 4. 1.]
 [1. 1. 4.]]


In [52]:
B = np.array([5, 2, 9, 1])

print(np.sort(B))

[1 2 5 9]


#### Compatif de performance : produit matriciel


In [53]:
import random

In [54]:
# Création d'une matrice aléatoire sous forme de liste de listes
taille = 30
A = [[random.random() for _ in range(taille)] for _ in range(taille)]

In [55]:
print(A)

[[0.47308270724763224, 0.7268555995924146, 0.17978971026701263, 0.13655989980737215, 0.6255930598981863, 0.9349546276198274, 0.901046811877003, 0.36245311565602845, 0.5269387280575131, 0.4565102900625472, 0.15514095777832726, 0.7561488216548671, 0.24430179585896017, 0.775370903167984, 0.4591125023942869, 0.4631117411068292, 0.8567966861025755, 0.4949477399741934, 0.5490866568486948, 0.4540394189263005, 0.003406306215103738, 0.5088228115244731, 0.18628419530673646, 0.336024518063772, 0.2784752516535465, 0.18641385115798204, 0.0769559712525475, 0.37834410740783675, 0.43114544160219637, 0.9007194942474911], [0.45373749911292227, 0.6066335036521916, 0.22400934143309503, 0.9082169854673634, 0.4979913480693562, 0.1695028621942144, 0.6713217402890201, 0.6768189484708044, 0.04827117511949919, 0.37788609386887795, 0.9162308901546982, 0.9618153492481853, 0.16596323680024205, 0.9670203427676907, 0.9715171904236863, 0.20703393404728887, 0.4138895031682168, 0.9213963677722049, 0.11342278241092896, 

In [56]:
"""
EXERCICE - Afficher un tuple contenant les dimensions de la matrice A
"""
A=np.array(A)
print(A.shape)


(30, 30)


$$ (AB)_{ij} = \sum_k A_{ik} B_{kj} $$

In [57]:
"""
EXERCICE - Implémenter le produit matriciel de 2 matrices sous forme de listes de listes python
"""
def produit(A,B):
    A=np.array(A)
    B=np.array(B)
    l_A=A.shape[0]
    c_A=A.shape[1]
    c_B=B.shape[1]
    C=np.zeros((l_A,c_B))
    for i in range(l_A):
        for k in range(c_A):
            for j in range(c_B):
                C[i][j]+=A[i][k]*B[k][j]
    return C.tolist()

In [58]:
# Vérification
assert(produit([[1, 2], [3, 4]], [[1, 2], [3, 4]]) == [[7, 10], [15, 22]])

In [59]:
produit(A, A)

[[7.044940042324607,
  6.600965691599459,
  5.589046515004929,
  5.883083489944305,
  5.698048357821686,
  5.801345361744786,
  7.752577515574566,
  7.43517357110795,
  6.901056181528994,
  6.333292929621215,
  6.250660763036651,
  6.899324864372041,
  6.774291946035457,
  7.794458635864895,
  6.885829385750443,
  6.880045478449314,
  6.818740603030117,
  7.4298179914873455,
  5.9551657340649555,
  7.112282109683516,
  5.173230662629545,
  6.947151026163762,
  6.329506583653576,
  6.455019187566453,
  6.116700194211461,
  7.991893366364231,
  6.416804568928243,
  6.4560449255842585,
  7.042293432257371,
  6.937478925675955],
 [8.14537578492368,
  7.075185921401695,
  6.206082971452281,
  5.807346921964452,
  7.553734808145192,
  7.600033585712796,
  9.267709540329442,
  9.604160283367845,
  7.6854458145536135,
  5.600529650401735,
  6.8948131595909485,
  7.3307860893532455,
  7.886591846527339,
  9.719082001877315,
  6.95457160273974,
  8.390209417477896,
  6.89945462353949,
  9.318374

In [60]:
# Sortons le chronomètre
%timeit produit(A, A)

13.2 ms ± 204 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [61]:
# Et maintenant, avec numpy !
import numpy as np

In [62]:
A2 = np.array(A)
print(A2)

[[0.47308271 0.7268556  0.17978971 0.1365599  0.62559306 0.93495463
  0.90104681 0.36245312 0.52693873 0.45651029 0.15514096 0.75614882
  0.2443018  0.7753709  0.4591125  0.46311174 0.85679669 0.49494774
  0.54908666 0.45403942 0.00340631 0.50882281 0.1862842  0.33602452
  0.27847525 0.18641385 0.07695597 0.37834411 0.43114544 0.90071949]
 [0.4537375  0.6066335  0.22400934 0.90821699 0.49799135 0.16950286
  0.67132174 0.67681895 0.04827118 0.37788609 0.91623089 0.96181535
  0.16596324 0.96702034 0.97151719 0.20703393 0.4138895  0.92139637
  0.11342278 0.53634166 0.74858325 0.32746816 0.32524637 0.20240006
  0.81060387 0.67999724 0.89540147 0.15176319 0.59386853 0.42678504]
 [0.12528572 0.12440237 0.36197608 0.55712036 0.98373192 0.98065942
  0.33108459 0.95742665 0.24159422 0.69875265 0.44283039 0.47784736
  0.12829937 0.60827229 0.20163787 0.13660873 0.12886518 0.66054001
  0.42521398 0.0287658  0.98949705 0.50331785 0.4950362  0.96055663
  0.74243786 0.35730754 0.32067301 0.71626956 

In [63]:
%timeit np.dot(A, A)

3.03 µs ± 19.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


EXERCICE - Remplissez le tableau suivant avec les durées d'exécution constatées :

(Conseil : pour la taille 3000, essayez UNIQUEMENT avec numpy)

Taille | Python | numpy
-------|--------|-------
30     | 23.3 ms ± 228 µs    | 184 µs ± 1.35 µs
300    | 22.2 s ± 47.1 ms   | 14.9 ms ± 44.6 µs
3000   | XXX    | 1.82 s ± 36.1 ms

###  Pandas

In [64]:
import pandas as pd

In [65]:
df_exemple = pd.DataFrame({"ESN": ["E420912", "E420913", "E420914"], "panne": [False, False, True]})
df_exemple

ESN  panne
0  E420912  False
1  E420913  False
2  E420914   True

#### Lecture et prétraitement de données


In [66]:
!git clone https://github.com/MadaneA/MACS3-Statistiques-Descriptives-TDs.git

fatal: destination path 'MACS3-Statistiques-Descriptives-TDs' already exists and is not an empty directory.


In [67]:
import os
os.chdir('MACS3-Statistiques-Descriptives-TDs')

In [68]:
 os.getcwd()

'/Users/abanishbaskaradevan/Dossier Pages Sur Ordinateur/MACS 3/TD Statistique/MACS3-Statistiques-Descriptives-TDs'

In [69]:
# Chargement d'un fichier CSV ou Excel
df = pd.read_csv("./data/Vol010.csv")
# Affichage des 5 premières lignes
df.head()

t EGT_SEL FLIGHT_MOD FMV_SEL HPTC_SEL LPTC_SEL  \
0                  datenum   deg_C          _       _        %        %   
1  15/09/2011 14:25:58.125     NaN        NaN     NaN      NaN      NaN   
2  15/09/2011 14:25:58.375     NaN        NaN     NaN      NaN      NaN   
3  15/09/2011 14:25:58.625     NaN        NaN     NaN      NaN      NaN   
4  15/09/2011 14:25:58.875     NaN        NaN     NaN      NaN      NaN   

  N1_SEL N2_ACTSEL OIL_P OIL_TEMP  ... T25_SEL T3_SEL VBV_SEL VIB_CN1 VIB_CN2  \
0      %     %_RPM   psi        _  ...       _      _     DEG       _       _   
1    NaN         0   NaN      NaN  ...     NaN    NaN     NaN     NaN     NaN   
2    NaN         0   NaN      NaN  ...     NaN    NaN     NaN     NaN     NaN   
3    NaN         0   NaN      NaN  ...     NaN    NaN     NaN     NaN     NaN   
4    NaN         0   NaN      NaN  ...     NaN    NaN     NaN     NaN     NaN   

  VIB_TN1 VIB_TN2 VSV_SEL  WFM_SEL    XM  
0       _       _     DEG     lb/h  mach  
1     NaN     NaN     NaN      NaN   NaN  
2     NaN     NaN     NaN      NaN   NaN  
3     NaN     NaN     NaN      NaN   NaN  
4     NaN     NaN     NaN  7679.98  0.15  

[5 rows x 26 columns]

In [70]:
"""
EXERCICE - Dimensions d'un DataFrame
Affichez le nombre de colonnes et de ligne du DataFrame (indice : beaucoup de méthodes sont communes entre numpy et pandas)
"""
#raise NotImplementedError
print('Nombre de colonnes :',df.shape[1] )
print('Nombre de lignes :', df.shape[0])

Nombre de colonnes : 26
Nombre de lignes : 22945


In [71]:
df.size, len(df)

(596570, 22945)

In [72]:
df.columns

Index(['t', 'EGT_SEL', 'FLIGHT_MOD', 'FMV_SEL', 'HPTC_SEL', 'LPTC_SEL',
       'N1_SEL', 'N2_ACTSEL', 'OIL_P', 'OIL_TEMP', 'PS3_SEL', 'PT2_SEL',
       'P0_SEL', 'TAT', 'TBV_SEL', 'TRA_SEL', 'T25_SEL', 'T3_SEL', 'VBV_SEL',
       'VIB_CN1', 'VIB_CN2', 'VIB_TN1', 'VIB_TN2', 'VSV_SEL', 'WFM_SEL', 'XM'],
      dtype='object')

Les colonnes des DF sont typées, à la manière d'une base de données relationnelle, contrairement aux variables python classiques. Les types des colonnes sont accessibles via df.dtypes. Les principaux types sont les numériques (int32, int64, float etc.

In [73]:
df.loc[10:15, ['EGT_SEL', 'FLIGHT_MOD']]

EGT_SEL FLIGHT_MOD
10    0.00234327        NaN
11  1.08032e-007        NaN
12  3.12514e-012        NaN
13             0        NaN
14       72.0006        NaN
15       215.996        NaN

In [74]:
"""
EXERCICE - Extraction et suppression des unités
On remarque que la 1ère ligne ne contient pas de données mais les unités de chaque colonne.
Pour la suite des traitements, il faut supprimer cette ligne. On souhaite toutefois garder l'information des unités de chaque colonne.
1. Récupérez les unités et stockez les dans une structure adaptée.
2. Supprimez cette ligne du DataFrame en utilisant la méthode "drop"
"""
df.values[0]
df.columns
units=dict([(df.columns[i],df.values[0][i]) for i in range(df.shape[1])])
df=df.drop([0])
#raise NotImplementedError


In [75]:
print(units)
df.head()

{'t': 'datenum', 'EGT_SEL': 'deg_C', 'FLIGHT_MOD': '_', 'FMV_SEL': '_', 'HPTC_SEL': '%', 'LPTC_SEL': '%', 'N1_SEL': '%', 'N2_ACTSEL': '%_RPM', 'OIL_P': 'psi', 'OIL_TEMP': '_', 'PS3_SEL': 'psi', 'PT2_SEL': 'mb', 'P0_SEL': 'psi', 'TAT': 'deg_C', 'TBV_SEL': '%', 'TRA_SEL': 'DEG', 'T25_SEL': '_', 'T3_SEL': '_', 'VBV_SEL': 'DEG', 'VIB_CN1': '_', 'VIB_CN2': '_', 'VIB_TN1': '_', 'VIB_TN2': '_', 'VSV_SEL': 'DEG', 'WFM_SEL': 'lb/h', 'XM': 'mach'}


t EGT_SEL FLIGHT_MOD FMV_SEL HPTC_SEL LPTC_SEL  \
1  15/09/2011 14:25:58.125     NaN        NaN     NaN      NaN      NaN   
2  15/09/2011 14:25:58.375     NaN        NaN     NaN      NaN      NaN   
3  15/09/2011 14:25:58.625     NaN        NaN     NaN      NaN      NaN   
4  15/09/2011 14:25:58.875     NaN        NaN     NaN      NaN      NaN   
5  15/09/2011 14:25:59.125     NaN        NaN     NaN      NaN      NaN   

  N1_SEL N2_ACTSEL    OIL_P OIL_TEMP  ... T25_SEL T3_SEL VBV_SEL VIB_CN1  \
1    NaN         0      NaN      NaN  ...     NaN    NaN     NaN     NaN   
2    NaN         0      NaN      NaN  ...     NaN    NaN     NaN     NaN   
3    NaN         0      NaN      NaN  ...     NaN    NaN     NaN     NaN   
4    NaN         0      NaN      NaN  ...     NaN    NaN     NaN     NaN   
5      0         0  647.998      NaN  ...     NaN    NaN       0       0   

  VIB_CN2 VIB_TN1 VIB_TN2 VSV_SEL  WFM_SEL    XM  
1     NaN     NaN     NaN     NaN      NaN   NaN  
2     NaN     NaN     NaN     NaN      NaN   NaN  
3     NaN     NaN     NaN     NaN      NaN   NaN  
4     NaN     NaN     NaN     NaN  7679.98  0.15  
5       0       0       0       0  4607.86  0.15  

[5 rows x 26 columns]

On remarque que toutes les colonnes ont été reconnues comme de type object, c'est-à-dire des chaînes de caractères, alors que ce sont des valeurs numériques. Cela est dû à la première ligne contenant les unités. Il faut donc convertir les colonnes en numérique. La colonne 't', quant à elle, doit être convertie en type datetime.

In [76]:
df['t'] = pd.to_datetime(df['t'])
df[df.columns[1:]] = df[df.columns[1:]].apply(pd.to_numeric)

In [77]:
df.dtypes

t             datetime64[ns]
EGT_SEL              float64
FLIGHT_MOD           float64
FMV_SEL              float64
HPTC_SEL             float64
LPTC_SEL             float64
N1_SEL               float64
N2_ACTSEL            float64
OIL_P                float64
OIL_TEMP             float64
PS3_SEL              float64
PT2_SEL              float64
P0_SEL               float64
TAT                  float64
TBV_SEL              float64
TRA_SEL              float64
T25_SEL              float64
T3_SEL               float64
VBV_SEL              float64
VIB_CN1              float64
VIB_CN2              float64
VIB_TN1              float64
VIB_TN2              float64
VSV_SEL              float64
WFM_SEL              float64
XM                   float64
dtype: object

In [78]:
"""
Exercice - Index temporel
Comme nos données sont une série temporelle multivariée, on souhaite utiliser un index temporel.
1. Créez une copie de df, appelée df2, à l'aide de la méthode du même nom.
2. Affectez la colonne du temps ('t') en tant qu'indice du DataFrame.
3. Supprimez la colonne 't' du DF résultant.
"""
df2=df.copy()
df2.index=df2['t']
df2=df2.drop(['t'],axis=1)
df2.head()
#raise NotImplementedError

EGT_SEL  FLIGHT_MOD  FMV_SEL  HPTC_SEL  LPTC_SEL  \
t                                                                           
2011-09-15 14:25:58.125      NaN         NaN      NaN       NaN       NaN   
2011-09-15 14:25:58.375      NaN         NaN      NaN       NaN       NaN   
2011-09-15 14:25:58.625      NaN         NaN      NaN       NaN       NaN   
2011-09-15 14:25:58.875      NaN         NaN      NaN       NaN       NaN   
2011-09-15 14:25:59.125      NaN         NaN      NaN       NaN       NaN   

                         N1_SEL  N2_ACTSEL    OIL_P  OIL_TEMP  PS3_SEL  ...  \
t                                                                       ...   
2011-09-15 14:25:58.125     NaN        0.0      NaN       NaN      NaN  ...   
2011-09-15 14:25:58.375     NaN        0.0      NaN       NaN      NaN  ...   
2011-09-15 14:25:58.625     NaN        0.0      NaN       NaN      NaN  ...   
2011-09-15 14:25:58.875     NaN        0.0      NaN       NaN      NaN  ...   
2011-09-15 14:25:59.125     0.0        0.0  647.998       NaN  575.982  ...   

                         T25_SEL  T3_SEL  VBV_SEL  VIB_CN1  VIB_CN2  VIB_TN1  \
t                                                                              
2011-09-15 14:25:58.125      NaN     NaN      NaN      NaN      NaN      NaN   
2011-09-15 14:25:58.375      NaN     NaN      NaN      NaN      NaN      NaN   
2011-09-15 14:25:58.625      NaN     NaN      NaN      NaN      NaN      NaN   
2011-09-15 14:25:58.875      NaN     NaN      NaN      NaN      NaN      NaN   
2011-09-15 14:25:59.125      NaN     NaN      0.0      0.0      0.0      0.0   

                         VIB_TN2  VSV_SEL  WFM_SEL    XM  
t                                                         
2011-09-15 14:25:58.125      NaN      NaN      NaN   NaN  
2011-09-15 14:25:58.375      NaN      NaN      NaN   NaN  
2011-09-15 14:25:58.625      NaN      NaN      NaN   NaN  
2011-09-15 14:25:58.875      NaN      NaN  7679.98  0.15  
2011-09-15 14:25:59.125      0.0      0.0  4607.86  0.15  

[5 rows x 25 columns]

On constate que pandas a automatiquement reconnu un DatetimeIndex, adapté pour des manipulations de séries temporelles (moyennes glissantes, etc) !

### Valeurs manquantes

**NaN = Not a Number**

Les valeurs NaN doivent être éliminées ou imputées (i.e. remplacées par une certaine valeur) avant la suite des traitements. Ce choix dépend du cas d'usage. Dans un premier temps, nous allons apprendre à :

* trouver les données manquantes (méthode `isna`)
* éliminer les données manquantes d'un DataFrame (méthode `dropna`)
* les remplacer par une constante (méthode (`fillna`)

In [79]:
"""
EXERCICE - La méthode isna
1. Testez la méthode isna sur le DataFrame df2, puis sur une colonne ou une ligne. Que renvoie-t-elle ?
2. En appliquant les méthodes any(axis=...), mean() et max()/idxmax() sur les résultats de isna(), répondez aux questions suivantes :
    2.1 Quelles colonnes contiennent des valeurs manquantes, lesquelles n'en contiennent pas ?
    2.2 Quel est le pourcentage de valeurs manquantes dans le DF (a) par colonne (b) globalement ? Quelle variable contient le plus de NaN ?
    2.3 Quel est le pourcentage d'indices du DF pour lesquels toutes les variables sont présentes ?
"""



"\nEXERCICE - La méthode isna\n1. Testez la méthode isna sur le DataFrame df2, puis sur une colonne ou une ligne. Que renvoie-t-elle ?\n2. En appliquant les méthodes any(axis=...), mean() et max()/idxmax() sur les résultats de isna(), répondez aux questions suivantes :\n    2.1 Quelles colonnes contiennent des valeurs manquantes, lesquelles n'en contiennent pas ?\n    2.2 Quel est le pourcentage de valeurs manquantes dans le DF (a) par colonne (b) globalement ? Quelle variable contient le plus de NaN ?\n    2.3 Quel est le pourcentage d'indices du DF pour lesquels toutes les variables sont présentes ?\n"

In [80]:
print(df2.isna())

                         EGT_SEL  FLIGHT_MOD  FMV_SEL  HPTC_SEL  LPTC_SEL  \
t                                                                           
2011-09-15 14:25:58.125     True        True     True      True      True   
2011-09-15 14:25:58.375     True        True     True      True      True   
2011-09-15 14:25:58.625     True        True     True      True      True   
2011-09-15 14:25:58.875     True        True     True      True      True   
2011-09-15 14:25:59.125     True        True     True      True      True   
...                          ...         ...      ...       ...       ...   
2011-09-15 16:01:32.875     True        True     True      True      True   
2011-09-15 16:01:33.125     True        True     True      True      True   
2011-09-15 16:01:33.375     True        True     True      True      True   
2011-09-15 16:01:33.625     True        True     True      True      True   
2011-09-15 16:01:33.875     True        True     True      True      True   

In [81]:
print(pd.isna(df2.values[1]))

[ True  True  True  True  True  True False  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True]


In [82]:
print(pd.isna(df2.values[:][4]))

[ True  True  True  True  True False False False  True False  True  True
 False False False  True  True False False False False False False False
 False]


Elle renvoie un booleen (True s'il y a des Nan False sinon)

In [83]:
print('Question 2.1')
#raise NotImplementedError
print(df2.isna().all())

Question 2.1
EGT_SEL       False
FLIGHT_MOD    False
FMV_SEL       False
HPTC_SEL      False
LPTC_SEL      False
N1_SEL        False
N2_ACTSEL     False
OIL_P         False
OIL_TEMP      False
PS3_SEL       False
PT2_SEL       False
P0_SEL        False
TAT           False
TBV_SEL       False
TRA_SEL       False
T25_SEL       False
T3_SEL        False
VBV_SEL       False
VIB_CN1       False
VIB_CN2       False
VIB_TN1       False
VIB_TN2       False
VSV_SEL       False
WFM_SEL       False
XM            False
dtype: bool


In [84]:
print('Question 2.2')
print("Le pourcentage de valeurs manquantes dans le DF par colonne est ",df2.isna().mean()*100)
print("Le pourcentage de valeurs manquantes dans le DF globalement est ",df2.isna().mean().mean()*100)
print("La variable qui contient le plus de Nan est : ",df2.isna().mean().idxmax())
#raise NotImplementedError

Question 2.2
Le pourcentage de valeurs manquantes dans le DF par colonne est  EGT_SEL       0.348675
FLIGHT_MOD    0.444561
FMV_SEL       0.444561
HPTC_SEL      0.422768
LPTC_SEL      0.457636
N1_SEL        0.418410
N2_ACTSEL     0.252789
OIL_P         0.379184
OIL_TEMP      0.383543
PS3_SEL       0.300732
PT2_SEL       0.370467
P0_SEL        0.370467
TAT           0.300732
TBV_SEL       0.296374
TRA_SEL       0.300732
T25_SEL       0.470711
T3_SEL        0.470711
VBV_SEL       0.292015
VIB_CN1       0.292015
VIB_CN2       0.283298
VIB_TN1       0.283298
VIB_TN2       0.283298
VSV_SEL       0.274582
WFM_SEL       0.270223
XM            0.261506
dtype: float64
Le pourcentage de valeurs manquantes dans le DF globalement est  0.346931659693166
La variable qui contient le plus de Nan est :  T25_SEL


In [85]:
print('Question 2.3')
#raise NotImplementedError

Question 2.3


In [86]:
"""
EXERCICE - La méthode dropna
La méthode dropna permet d'éliminer les valeurs manquantes (NaN). Lisez d'abord sa documentation.
1. À quoi correspondent les arguments "axis" et "how" ?
2. Éliminez toutes les lignes contenant uniquement des valeurs manquantes.
3. Éliminez toutes les lignes contenant au moins une valeur manquante. Combien y a-t-il de lignes de différence ?
4. Éliminez toutes les colonnes contenant au moins une valeur manquante.
"""


#raise NotImplementedError

'\nEXERCICE - La méthode dropna\nLa méthode dropna permet d\'éliminer les valeurs manquantes (NaN). Lisez d\'abord sa documentation.\n1. À quoi correspondent les arguments "axis" et "how" ?\n2. Éliminez toutes les lignes contenant uniquement des valeurs manquantes.\n3. Éliminez toutes les lignes contenant au moins une valeur manquante. Combien y a-t-il de lignes de différence ?\n4. Éliminez toutes les colonnes contenant au moins une valeur manquante.\n'

Question 1 

Axis correspond à la ligne (axis=0) ou colonne (axis=1)

how correspond si la ligne ou colonne correspondant contient que des Nan (how=all) ou s'il existe un Nan (how=any)

In [87]:
print("Question 2")
print(df2.dropna(how="all"))

Question 2
                         EGT_SEL  FLIGHT_MOD  FMV_SEL  HPTC_SEL  LPTC_SEL  \
t                                                                           
2011-09-15 14:25:58.125      NaN         NaN      NaN       NaN       NaN   
2011-09-15 14:25:58.375      NaN         NaN      NaN       NaN       NaN   
2011-09-15 14:25:58.625      NaN         NaN      NaN       NaN       NaN   
2011-09-15 14:25:58.875      NaN         NaN      NaN       NaN       NaN   
2011-09-15 14:25:59.125      NaN         NaN      NaN       NaN       NaN   
...                          ...         ...      ...       ...       ...   
2011-09-15 16:01:23.625      NaN         NaN      NaN       NaN       NaN   
2011-09-15 16:01:23.875      NaN         NaN      NaN       NaN       NaN   
2011-09-15 16:01:24.125      NaN         NaN      NaN       NaN       NaN   
2011-09-15 16:01:24.375      NaN         NaN      NaN       NaN       NaN   
2011-09-15 16:01:24.625      NaN         NaN      NaN       NaN  

In [88]:
print("Question 3")
print(df2.dropna(how="any"))
print(len(df2.axes[0])-len(df2.dropna(how="any").axes[0]))

Question 3
                          EGT_SEL  FLIGHT_MOD  FMV_SEL  HPTC_SEL  LPTC_SEL  \
t                                                                            
2011-09-15 14:26:02.875  335.9840         1.0    0.000       0.0       0.0   
2011-09-15 14:26:03.125  239.9860         1.0    0.000       0.0       0.0   
2011-09-15 14:26:03.375  167.9910         1.0    0.000       0.0       0.0   
2011-09-15 14:26:03.625  119.9940         1.0    0.000       0.0       0.0   
2011-09-15 14:26:03.875   72.0011         1.0    0.000       0.0       0.0   
...                           ...         ...      ...       ...       ...   
2011-09-15 16:01:19.875  230.8250         1.0  -12.375       0.0       0.0   
2011-09-15 16:01:20.125  137.4770         1.0  -12.375       0.0       0.0   
2011-09-15 16:01:20.375  113.4530         1.0  -12.375       0.0       0.0   
2011-09-15 16:01:20.625  158.8080         1.0  -12.375       0.0       0.0   
2011-09-15 16:01:20.875  204.1800         1.0  -12.37

In [89]:
print("Question 4")
print(df2.dropna(axis=1,how="any"))

Question 4
Empty DataFrame
Columns: []
Index: [2011-09-15 14:25:58.125000, 2011-09-15 14:25:58.375000, 2011-09-15 14:25:58.625000, 2011-09-15 14:25:58.875000, 2011-09-15 14:25:59.125000, 2011-09-15 14:25:59.375000, 2011-09-15 14:25:59.625000, 2011-09-15 14:25:59.875000, 2011-09-15 14:26:00.125000, 2011-09-15 14:26:00.375000, 2011-09-15 14:26:00.625000, 2011-09-15 14:26:00.875000, 2011-09-15 14:26:01.125000, 2011-09-15 14:26:01.375000, 2011-09-15 14:26:01.625000, 2011-09-15 14:26:01.875000, 2011-09-15 14:26:02.125000, 2011-09-15 14:26:02.375000, 2011-09-15 14:26:02.625000, 2011-09-15 14:26:02.875000, 2011-09-15 14:26:03.125000, 2011-09-15 14:26:03.375000, 2011-09-15 14:26:03.625000, 2011-09-15 14:26:03.875000, 2011-09-15 14:26:04.125000, 2011-09-15 14:26:04.375000, 2011-09-15 14:26:04.625000, 2011-09-15 14:26:04.875000, 2011-09-15 14:26:05.125000, 2011-09-15 14:26:05.375000, 2011-09-15 14:26:05.625000, 2011-09-15 14:26:05.875000, 2011-09-15 14:26:06.125000, 2011-09-15 14:26:06.375000, 2

In [90]:
"""
EXERCICE - La méthode fillna
La méthode dropna permet d'imputer les valeurs manquantes (NaN). Lisez d'abord sa documentation.
1. Quelles sont les différentes stratégies de remplissage des valeurs manquantes ?
2. Imputez les valeurs manquantes de la colonne age du DF donné en exemple par :
    - 0
    - la dernière valeur précédente/suivante valide
    - la moyenne
    - la valeur la plus courante (mode)
3. Quel est le meilleur choix dans ce cas ? Et pour le cas d'une variable temporelle, par exemple la température 'EGT_SEL' de notre jeu de données ?
"""
exemple = pd.DataFrame({'nom': ['Alice', 'Bob', 'Charlie', 'David'], 'age': [24, pd.np.nan, 99, 24]})

#raise NotImplementedError




/var/folders/fl/71zh2c117r9f2nwvtqmpm3nm0000gn/T/ipykernel_95600/3612850933.py:12: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead.
  exemple = pd.DataFrame({'nom': ['Alice', 'Bob', 'Charlie', 'David'], 'age': [24, pd.np.nan, 99, 24]})


Question 1 

Pour remplir les valeurs manquantes, on peut les remplir par des -1 ou $±\infty$

In [91]:
print("Question 2")
exemple.fillna(0)

Question 2


nom   age
0    Alice  24.0
1      Bob   0.0
2  Charlie  99.0
3    David  24.0

In [92]:
exemple.fillna(exemple.mean())

/var/folders/fl/71zh2c117r9f2nwvtqmpm3nm0000gn/T/ipykernel_95600/166453065.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  exemple.fillna(exemple.mean())


nom   age
0    Alice  24.0
1      Bob  49.0
2  Charlie  99.0
3    David  24.0

In [93]:
exemple.fillna(-1)

nom   age
0    Alice  24.0
1      Bob  -1.0
2  Charlie  99.0
3    David  24.0

In [94]:
exemple.fillna(np.inf)

nom   age
0    Alice  24.0
1      Bob   inf
2  Charlie  99.0
3    David  24.0

## Git

Créer un compte GitHub : https://github.com/

Créer un nouveau repository :
1. Sélectionner "Nouveau dépôt" dans le menu déroulant avec le signe +. 
2. Saisisser un nom pour votre dépôt (par exemple, "TDs statistiques descriptives") 
3. Cliquer sur "Créer un dépôt". Ne vous souciez pas des autres options.



Télécharger Git Bash : https://git-scm.com/downloads

Sur Git Bash, positionnez-vous dans le répertoire où votre projet figure.

Ensuite

> git init

> git remote add origin https://github.com/********

> git add .

> git commit -m "Ajout du TD1"

> git push origin master

C'est tout ! Vous avez créé votre repo GitHub ! 